spring.application.name=eventcart
server.port=8080

# ===============================
# Import CSI-mounted secrets
# ===============================
spring.config.import=optional:configtree:/mnt/secrets/