# =========================
# DEV ENVIRONMENT CONFIG
# =========================

server.port=8080

# ===============================
# Import CSI-mounted secrets
# ===============================
spring.config.import=optional:configtree:/mnt/secrets/
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/school
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000 
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.test-while-idle=true
spring.datasource.hikari.test-on-borrow=true
spring.datasource.hikari.connection-test-query=SELECT 1

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#logging.level.root=INFO
#logging.level.org.springframework.web=DEBUG