apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: ${NAMESPACE}
spec:
  provider: aws

  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:221082203021:secret:aws-dev-TTqsoc"
        objectType: "secretsmanager"
        jmesPath:
          - path: DB_HOST
            objectAlias: DB_HOST
          - path: DB_PORT
            objectAlias: DB_PORT
          - path: DB_USERNAME
            objectAlias: DB_USERNAME
          - path: DB_PASSWORD
            objectAlias: DB_PASSWORD
          - path: BUCKET_NAME
            objectAlias: BUCKET_NAME
          - path: QUEUE_NAME
            objectAlias: QUEUE_NAME

  secretObjects:
    - secretName: aws-secrets-env
      type: Opaque
      data:
        - objectName: DB_HOST
          key: DB_HOST
        - objectName: DB_PORT
          key: DB_PORT
        - objectName: DB_USERNAME
          key: DB_USERNAME
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: BUCKET_NAME
          key: BUCKET_NAME
        - objectName: QUEUE_NAME
          key: QUEUE_NAME