apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: ${NAMESPACE}

spec:
  provider: aws

  parameters:
    objects: |
      - objectName: "aws-${NAMESPACE}"
        objectType: "secretsmanager"
        jmesPath:
          - path: DB_HOST
            objectAlias: DB_HOST
          - path: DB_PORT
            objectAlias: DB_PORT
          - path: DB_USERNAME
            objectAlias: DB_USERNAME
          - path: DB_PASSWORD
            objectAlias: DB_PASSWORD
          - path: BUCKET_NAME
            objectAlias: BUCKET_NAME
          - path: QUEUE_NAME
            objectAlias: QUEUE_NAME