apiVersion: v1
kind: Service
metadata:
  name: eventcart-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: eventcart
  ports:
    - port: 80
      targetPort: 8080